[package]
name = "oxide-core-camera"
description = "Oxide Core camera components, controllers, and GPU camera buffers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "oxide_camera"

[dependencies]
oxide_ecs.workspace = true
oxide_input.workspace = true
oxide_math.workspace = true
bytemuck.workspace = true
glam.workspace = true
wgpu.workspace = true
winit.workspace = true
